const keywords = [
  // First: matching your 20 keywords, in order
  "anxiety",
  "depression",
  "stress",
  "trauma",
  "grief",
  "sadness",
  "anger",
  "fear",
  "worry",
  "relationships", // plural here matches your keyword intent
  "breakup",
  "self-esteem",
  "confidence",
  "panic",
  "loneliness",
  "abuse",
  "healing",
  "coping",
  "mindfulness",
  "therapy",

  // Then: remaining words from your full 100-word list (in any order since no sort requested beyond first part)
  "mental health",
  "emotional support",
  "self-esteem",
  "PTSD",
  "CBT",
  "DBT",
  "loss",
  "coping mechanisms",
  "meditation",
  "relaxation",
  "breathing exercises",
  "stress management",
  "burnout",
  "self-care",
  "conflict resolution",
  "anger management",
  "emotional regulation",
  "mood tracking",
  "journaling",
  "guided journaling",
  "inner child",
  "grounding techniques",
  "panic attacks",
  "social anxiety",
  "phobias",
  "motivation",
  "personal growth",
  "self-discovery",
  "acceptance",
  "validation",
  "empathy",
  "active listening",
  "non-judgmental",
  "supportive",
  "compassion",
  "affirmation",
  "positive psychology",
  "hope",
  "trust issues",
  "childhood trauma",
  "emotional wounds",
  "therapy chatbot",
  "crisis support",
  "mental wellness",
  "mental fitness",
  "safe space",
  "resilience",
  "encouragement",
  "suicidal thoughts",
  "emotional intelligence",
  "self-awareness",
  "guilt",
  "shame",
  "intrusive thoughts",
  "overthinking",
  "boundaries",
  "toxic relationships",
  "breakup recovery",
  "communication skills",
  "support system",
  "therapy session",
  "reflective listening",
  "mood swings",
  "mental clarity",
  "self-reflection",
  "personal goals",
  "daily check-in",
  "thought diary",
  "wellness routine",
  "self-improvement",
  "growth mindset",
  "self-compassion",
  "inner peace",
  "emotional pain",
  "validation loop",
  "calming voice",
  "trauma-informed",
  "somatic therapy",
  "healing journey",
  "therapist suggestions",
  "behavioral patterns",
  "negative self-talk",
  "reframing thoughts",
  "exposure therapy",
  "journaling prompts",
  "therapy assistant",
  "empathy mapping",
  "emotional triggers",
  "support journal",
  "gratitude practice",
  "healing affirmations",
  "guided reflection",
  "stability",
  "trust building",
  "self-regulation",
  "emotional safety",
  "recovery tracking",
  "therapeutic dialogue"
];


function filterTherapy(text) {
  const lower = text.toLowerCase();
  return keywords.some(kw => lower.includes(kw));
}

module.exports = { filterTherapy };